from detectron2.config import CfgNode as CN

def add_contacthands_config(cfg):

    _C = cfg
    _C.MODEL.CONTACT_HEAD_ON = True
    _C.MODEL.ROI_CONTACT_HEAD = CN()
    _C.MODEL.ROI_CONTACT_HEAD.NAME=""
    _C.MODEL.ROI_CONTACT_HEAD.POOLER_RESOLUTION = 7
    _C.MODEL.ROI_CONTACT_HEAD.POOLER_SAMPLING_RATIO = 0
    _C.MODEL.ROI_CONTACT_HEAD.POOLER_TYPE = "ROIAlignV2"
    _C.MODEL.ROI_CONTACT_HEAD.USE_INTERSECTION = False
    _C.MODEL.ROI_CONTACT_HEAD.LOSS_WEIGHT = 1.0
    _C.MODEL.ROI_CONTACT_HEAD.POS_WEIGHT = []
    _C.MODEL.ROI_CONTACT_HEAD.HAND_FCS = [1024]
    _C.MODEL.ROI_CONTACT_HEAD.HAND_OBJECT_FCS = [1024]
    _C.MODEL.ROI_CONTACT_HEAD.NUM_SPATIAL_ATTENTION = 32
    _C.MODEL.ROI_CONTACT_HEAD.CROSS_ATTENTION_FCS = [1024]
    _C.MODEL.ROI_CONTACT_HEAD.PROJECT_DIMS = []